// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrklkknipbhnmjihldsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impya2xra25pcGJobm1qaWhsZHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mjg1MjUsImV4cCI6MjA3MzUwNDUyNX0.LYdg-3kAQb1_Kn5w91vhj8pQksovGhAcuqYAq0x7P9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});